### PR TITLE
Multi item placement component - for ceramics production

### PR DESCRIPTION
**Pull request by Matt95**
Adds ability to place multiple media objects in target areas.

Overview: https://1drv.ms/b/s!AjpHaTFlEKBwkYUhJjGjOO5lnpLsgw

Example Scene: sizetest_matt33

### CODE REVIEW

**Comment by aaronpcz** [comment]
Had a good test, looking good so far.

Will complete review in the AM tomorrow

**Comment by Matt95** [comment]
Thanks. By the way does the Random Visual Player only randomise position and not sequence, I'm seeing a noticeable loop?

**Comment by Matt95** [comment]
Sorry lots of extra features added last minuet. I'm thinking it's worth doing the tag matcher (probably an hour or 2 of work) and then that's about the limit of what can be done in the existing setup.

**Comment by Matt95** [comment]
UI inside the targets is definitely cluttered but just about workable.

**Comment by aaronpcz** [comment]
@Matt95 Nice updates, more than happy for refinement before approve + deploy. 

I'll do some more retesting, I have a bit of CSS to add today as well.

**Pull request merged**
