### PR TITLE
Core 140 jpeg

### PR DESCRIPTION
**Pull request by PandaCoffeeBara**
JPEG added as an accepted type

### CODE REVIEW

**Comment by Stormgun** [comment]
Just as additional information I think this PR should go into master

**Comment by aaronpcz** [comment]
This is also doubling as a dev -> master release.

I'm OK with this, it needs to happen anyway.  We have some unreleased performance fixes for the playback.

**Comment by aaronpcz** [comment]
Would be good to get a second pair of eyes for the dev -> master work.

Worth testing (deployed dev) does basic scene preview playback as expected.  @Stormgun Can you spent 20 mins today just making sure dev scenes are fine.  This will require the assets to be stored as dev assets.. ie the urls aren't from live.

**Comment by Stormgun** [comment]
I will put into my work today, probably will go through this after lunch.

**Comment by aaronpcz** [comment]
How did the testing go?

**Comment by Stormgun** [comment]
So the assets need to be transferred over to the dev asset store and the links need to be updated with the dev url

**Comment by Stormgun** [comment]
We need to find a way to resolve this soon, so we can have proper database assets linked up to the scenes there, as its dev, it will be used for testing.

**Pull request closed without merging**
